version: '3.8'
services:
  backend:
    build: ./backend
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - default
      - web

networks:
  web:
    external:
      name: reverse-proxy_web